### PR TITLE
adding load config from module or py-file

### PR DESCRIPTION
**Pull request by ali96343**
to load gunicorn  config from a python file
or python module
It is necessary to write
export GUNICORN_use_native_config=myconf.py
export GUNICORN_use_native_config=python:mod_name

or write to gunicorn.saenv
export GUNICORN_use_native_config=myconf.py
export GUNICORN_use_native_config=python:mod_name
or
use_native_config=myconf.py
use_native_config=python:mod_name

### CODE REVIEW

**Comment by ali96343** [comment]
tested with config
https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py

**Comment by ali96343** [comment]
added variable use_python_config  == use_native_config
The first variable in the py4web/gunicorn.saenv  will be used

**Comment by mdipierro** [comment]
Thank you Ali. I am happy to merge this but can I ask you to include instructions in the the rst manual?

**Comment by ali96343** [comment]
The instructions are in the py4web/gunicorn.rst file

**Comment by mdipierro** [comment]
thanks!

**Pull request merged**
