### PR TITLE
return error_page instead if setting response.body

### PR DESCRIPTION
**Pull request by valq7711**

### CODE REVIEW

**Comment by valq7711** [comment]
fix #687

**Comment by Kkeller83** [comment]
I think it does.

If I remove e.g. an "a" from formstyle=FormStyleBulm instead of formstyle=FormStyleBulma for a form it gives me the 500 error with error ticket now. 

If I have an identantion error I get the red 400 page and see the error message only in the terminal. 

But I think this is how it used to be no?

I am justs not sure anymore for some reason. 

Ideally though the errors that produce the 400 should also create an error ticket no?

**Comment by Kkeller83** [comment]
Thank for the patch this was really cool you fixed it so fast.

**Comment by valq7711** [comment]
@Kkeller83 400? maybe 404  - not found, since indentation error is syntax error and if it is detected at loading time your app is not loaded at all

**Pull request merged**
