### PR TITLE
Auth API - Exposed Model Details

### PR DESCRIPTION
**Pull request by macneiln**
In reference to issue #445, this pull request simplifies some of the auth route exposure logic, as well as implementing a standard method for determining the model relating to exposed Auth API routes.

It functions similar to the [RestAPI](https://py4web.com/_documentation/static/en/chapter-08.html) by returning the API model when parameters **`@model=true`** are sent through in the request. 

**Details:**
- Query parameters **`@model=true`** can be appended to the end of exposed API routes to return the route model for that specific route or the front end can call the "all_models" route to obtain all exposed API route models at once (example below). 
 
**Request Examples:**
- `/auth/api/all_models` **(All exposed models)**
- `/auth/api/register?@model=true` **(Register model)**
- `/auth/api/login?@model=true` **(Login model)**
- `/auth/api/request_reset_password?@model=true` **(Request Reset Password model)**
- `/auth/api/reset_password?@model=true` **(Reset Password model)**
- `/auth/api/change_password?@model=true` **(Change Password model)**
- `/auth/api/profile?@model=true` **(Profile model)**
- `/auth/api/logout?@model=true` **(Logout model)**
- `/auth/api/verify_email?@model=true` **(Verify Email model)**

**Response Examples:**
- Dictionary response potentially containing:
    - **"fields"** array with the fields either visible/editable
    - **"additional_buttons"** array with buttons shown to the user on the corresponding standard auth route
    - **"href"** string for that route
    - **"submit_label"** string with details for that form submission button label
    - **"noform"**  boolean to easily identify routes without forms, i.e. logout/verify_email
    - **"public"**  boolean to determine whether this route should be shown if the user is logged out
    - **"hidden"**  boolean to determine if this is a standard route to shown in a menu list or a hidden route for special situations, i.e. verify_email and reset_password are only shown after they receive an email with a specific URL/token

**Miscellaneous:**
- The current "config" Auth API route should likely be removed as it doesn't seem to be used, or if it used it provides limited value to understanding the exposed routes and their details, which should now be handled but this updated functionality.

### CODE REVIEW

**Comment by macneiln** [comment]
**Example Output:**

---
**/auth/api/change_password?@model=true (Change Password model):**

image

---
**/auth/api/login?@model=true (Login model):**

image

---

**Comment by mdipierro** [comment]
wow excellent work. give me a day or two to review.

**Comment by macneiln** [comment]
Sounds good, thanks Massimo.

**Comment by Kkeller83** [comment]
Amazing work!

**Pull request merged**
