### PR TITLE
make watcher a separate service

### PR DESCRIPTION
**Pull request by valq7711**
This need to allow to use watcher with gevent (since asyncio doesn't work with gevent).

### CODE REVIEW

**Comment by mdipierro** [comment]
Can you please update the documentation accordingly?

**Comment by valq7711** [comment]
This only changes watcher implementation and doesn't affect on py4web run-options (now `--watch`-option works with gevent as well), so there is nothing  need to be updated in the docs. Maybe there is one point to discuss - now watcher runs as subprocess and communicates with py4web via `http://py4web_cli/<cmd>` - endpoint, which is exposed using bottle.route.

**Comment by mdipierro** [comment]
Please give me some time to evaluate any security implication of adding this endpoint.

**Comment by valq7711** [comment]
It is protected  by `cli_key` which should be passed in a custom header `X-Py4web-Cli-Key`

**Comment by Kkeller83** [comment]
Is this also something to consider? https://github.com/gfmio/asyncio-gevent

**Comment by valq7711** [comment]
Some clarifications:
This is very simple `HTTPCLI` class that provides low-level cli-interface to py4web (mainly for internal needs):
https://github.com/web2py/py4web/blob/429e12b9f071f849736051b1c3f985df3c9d83a5/py4web/core.py#L1273-L1312

`HTTPCLI.command` is a decorator, so you can anywhere:
```python
from py4web.core import HTTPCLI
    
@HTTPCLI.command
def echo(msg):
    return msg
```

`HTTPCLI.mount()` - actually  mounts endpoint 

`HTTPCLI.cli` - command processor that maps `<cmd>` to the function (which was exposed by `@HTTPCLI.command`)

The endpoint is protected by `HTTPCLI.cli_key`
https://github.com/web2py/py4web/blob/429e12b9f071f849736051b1c3f985df3c9d83a5/py4web/core.py#L1286-L1290

Usage example:

https://github.com/web2py/py4web/blob/429e12b9f071f849736051b1c3f985df3c9d83a5/py4web/watcher.py#L31-L42

**Comment by valq7711** [comment]
@Kkeller83 


> Is this also something to consider? https://github.com/gfmio/asyncio-gevent

I tried this first  - doesn't work on windows at least (import error  - it seems that it assumes asyncio old version)

**Comment by mdipierro** [comment]
this is good code but I feel it adds complexity that is not necessary and also exposes a service that one many now want exposed.

**Pull request closed without merging**
