### PR TITLE
form widgets in style - WIP - RFC

### PR DESCRIPTION
**Pull request by mdipierro**
This is an experiment. It would work as follows:

```
class MyCustomWidget:
    def make(self, field, value, error, title, placeholder, readonly=False):
           return INPUT(_name=field.name, _value=value)

MyStyle = FormStyleFactory()
MyStyle.classes = FormStyleBulma.classes
MyStyle.widgets['xyz'] = MyCustomWidget()
MyStyle.widgets['abc"] = RadioWidget()

form = Form([Field('xyz'), Field('abc', requires=IS_IN_SET(('a','b','c')))], formstyle=MyStyle)
```

Needs more testing before merging. If approved would supercede/include #525 and #529

### CODE REVIEW

**Comment by jpsteil** [comment]
Thanks Massimo! Excited to get started testing - no time today but hope to get time this week.

**Comment by Kkeller83** [comment]
Thank you Massimo!! Will be able to test on Wednesday!

**Comment by jpsteil** [comment]
I spent the afternoon working with this branch. I'm having trouble with the classes.  Seems like no matter what I do, the FormStyleXxxxx that appears last in the source seems to be the one that is used.  In my controller I have:

```
    formstyle = FormStyleFactory()
    formstyle.classes = FormStyleBulma.classes
    formstyle.class_inner_exceptions = FormStyleBulma.class_inner_exceptions
    formstyle.widgets['vendor'] = NewHtmxAutocompleteWidget()
    formstyle.widgets['product'] = NewHtmxAutocompleteWidget()

    form = Form(
        db.purchase_contract,
        record=purchase_contract,
        formstyle=formstyle,
        **attrs,
    )
```
But, I get the Bootstrap classes.  If I change the order they appear in form.py placing FormStyleBulma after FormStyleBootstrap4, then I get Bulma classes.

Also, this class in form.py
```
class Widget:
    type_map = {
        "string": "text",
        "date": "date",
        "time": "time",
        "integer": "text"
    }

    def make(self, field, value, error, title, placeholder="", readonly=False):
        return INPUT(
            _value=value,
            _type=self.type_map[field.type],
            _id=to_id(field),
            _name=field.name,
            _placeholder=placeholder,
            _title=title,
            _readonly=readonly,
        )
```
I changed to
```
class Widget:
    type_map = {
        "string": "text",
        "date": "date",
        "time": "time",
        "integer": "text"
    }

    def make(self, field, value, error, title, placeholder="", readonly=False):
        return INPUT(
            _value=value,
            _type=self.type_map.get(field.type, 'text'),
            _id=to_id(field),
            _name=field.name,
            _placeholder=placeholder,
            _title=title,
            _readonly=readonly,
        )
```
I was able to test a custom htmx autocomplete widget I've been working with and all works fine.

One other thing if you plan on keeping the old field.widget code. Can we get away with this change?

```
            # if we have a field.widget for the field use it but this logic is deprecated
            elif field.widget:
                control = field.widget(table, value)
```
to
```
            # if we have a field.widget for the field use it but this logic is deprecated
            elif field.widget:
                control = field.widget(field, vars)
```
this gives you more capabilities within the widget - it passes the specific field you're dealing with and ALL of the values. The way it is currently implemented I don't know which field I'm dealing with inside the widget. 

Not a huge deal, but if you plan on keeping the old widget mechanism, I think this should be considered.

**Comment by Kkeller83** [comment]
I get this error: 

File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/form.py", line 444, in __call__
    control = widget.make(field, value, error, title, placeholder)
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/form.py", line 169, in make
    values_dict = [
  File "/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/form.py", line 170, in <listcomp>
    [k, v, (not k is None and k in value)]
TypeError: argument of type 'NoneType' is not iterable

When using Radiowidgets in the controller: 

from py4web.utils.form import Form,FormStyleFactory, RadioWidget,FormStyleBulma


MyStyle = FormStyleFactory()
MyStyle.widgets['status'] = RadioWidget()
MyStyle.classes = FormStyleBulma.classes

@unauthenticated("index", "index.html")
def index():
    form=Form(db.presentationevent, formstyle=MyStyle)
    return dict(form=form)


and this model:

db.define_table(
'presentationevent',
    Field('creator', db.auth_user),
    Field('owner', db.auth_user),
    Field('title'),
    Field('startdate', 'datetime'),
    Field ('enddate', 'datetime'),
    Field('status',options=("On-Going", "On-Hold", "Ended")),
    Field('onhold','boolean',label='On-Hold?'),
    Field('endearly','boolean',label='End Event Early?'),
    Field ('description'),
    format='%(title)s')
db.presentationevent.status.requires=IS_IN_SET(('On-Going','On-Hold','Ended'))

**Comment by Kkeller83** [comment]
Jim and I were testing the FileUploadWidget as well and Jim found the following errors:

the "return control" is missing

The last 2 lines:

control.append(LABEL("Change: "))
control.append(INPUT(_type="file", _id=field_id, _name=field.name))

Need to be outside the IF and thus unindented.

Also deleting pictures does not work atm.

Corrected code so far:

class FileUploadWidget:
    def make(self, field, value, error, title, placeholder="", readonly=False):
        field_id = to_id(field)
        control = DIV()
        if value and not error:
            download_div = DIV()

            if not readonly:
                download_div.append(
                    LABEL(
                        "Currently:  ",
                    )
                )
            url = getattr(field, "download_url", lambda value: "#")(value)
            download_div.append(A(" download ", _href=url))

            if not readonly:
                download_div.append(
                    INPUT(
                        _type="checkbox",
                        _value="ON",
                        _name="_delete_" + field.name,
                        _title=title,
                    )
                )
                download_div.append(" (check to remove)")

            control.append(download_div)

        control.append(LABEL("Change: "))
        control.append(INPUT(_type="file", _id=field_id, _name=field.name))
        return control

**Comment by mdipierro** [comment]
Thanks for the bug report. I think it is all fixed. Can you try again. Do you agree to merge this?

**Comment by Kkeller83** [comment]
I still see the issue with the Formstyle classes, the Radiobutton and the deletion issue of images for Fileupload. Also line 61 in form.py does not include Jims fix:  _type=self.type_map.get(field.type, 'text'), which seems to be needed otherwise I get an error too. I have packed up your latest form.py with latest commits from this PR and the apps we use for testing (radiowidget (radiowidget test)  and py4web_htmx_demo (Formclasses test and line 61 error)  and covid_tourguides (Fileupload widget delete test): https://drive.google.com/file/d/1okxae5dTLXvdOZm_QUytAYqwtZKNqSId/view?usp=sharing

**Comment by Kkeller83** [comment]
In the zip file with the 3 testing apps I have already included Jims fix in line 61. If you change it back to _type=self.type_map[field.type] you will see the error when you go to "orders" then click on any name (Jim, Kevin, Massimo) and then try to edit an order item.

**Comment by Kkeller83** [comment]
Jim mentioned that the FormStyle class error may have something to do with Variable or Instance Class instantiation.

**Comment by Kkeller83** [comment]
This fixes the radiowidget: 

added line: 
value = list(map(str, value if isinstance(value, list) else [value]))

changed line:
from: 
for k, v, selected in field_options:

to:
for k, v, selected in field_options[1:]:



class RadioWidget:
    def make(self, field, value, error, title, placeholder="", readonly=False):
        control = DIV()
        field_id = to_id(field)
        value = list(map(str, value if isinstance(value, list) else [value]))
        field_options = [
            [k, v, (not k is None and k in value)]
            for k, v in get_options(field.requires)
        ]
        for k, v, selected in field_options[1:]:
            control.append(
                INPUT(
                    v,
                    _id=field_id,
                    _value=k,
                    _label=v,
                    _name=field.name,
                    _type="radio",
                    _checked=selected,
                )
            )
            control.append(LABEL(v, _for=field_id))
        return control

**Comment by Kkeller83** [comment]
Sorry Fileuploadimage delete works now all good with that too.   I had some more advanced form processing in my sample code with list of fields that had an error. My bad.

**Comment by mdipierro** [comment]
I should have addressed all concerns. Do you think this is fine to merge now? Do we need some additional functionality or convention that we want to enforce? Will this work well for your needs?

**Comment by Kkeller83** [comment]
Radiowidget still does not work. I think you need to add this:

added line:
value = list(map(str, value if isinstance(value, list) else [value]))

changed line:
from:
for k, v, selected in field_options:

to:
for k, v, selected in field_options[1:]:

I also do not still get the bootstrap4 theme even though FormStyleBulma is defined. 

I can test some more tomorrow morning

**Comment by mdipierro** [comment]
OK. I think I addressed them all now. :-)

**Comment by Kkeller83** [comment]
First element in the radio widget has to be skipped. In the selectfield an empty value is fine, but an empty radio widget does not look good. I think you also need to add this line please : for k, v, selected in field_options[1:]:.

**Comment by Kkeller83** [comment]
Have you tested the styling classes? In my tests in didn't work but it might be because I am testing the forms with Jim's grid. I can do a stand alone test tomrrow morning. Sorry I hope I'm not a pain. Thanks for putting up with me ')

**Comment by mdipierro** [comment]
Maybe I misunderstand where this first element comes from. If it is the zero element from the IS_IN_SET validator, it should have a key == "" and therefore should be removed by if k is not "". Is it no?

**Comment by mdipierro** [comment]
Did not test it but it was wrong and i changed.

**Comment by Kkeller83** [comment]
This is what I get now: 

Dashboard is at: http://127.0.0.1:8000/_dashboard
[ ] loading covid_tourguides ...
/Users/kkeller/Development/py4web_PRs/testing/py4web/py4web/utils/form.py:172: SyntaxWarning: "is not" with a literal. Did you mean "!="?
[FAILED] loading covid_tourguides ('FormStyleFactory' object has no attribute 'classes')
[FAILED] loading myfeed ('FormStyleFactory' object has no attribute 'classes')
[X] loaded _dashboard       
[X] loaded _documentation       
[X] loaded todo       
[X] loaded _default       
[X] loaded _minimal       
[FAILED] loading radiowidget ('FormStyleFactory' object has no attribute 'classes')
[FAILED] loading examples ('FormStyleFactory' object has no attribute 'classes')
[FAILED] loading _scaffold ('FormStyleFactory' object has no attribute 'classes')
[FAILED] loading py4web_htmx_demo ('FormStyleFactory' object has no attribute 'classes')
[X] loaded _websocket       
Bottle v0.12.18 server starting up (using TornadoServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

**Comment by Kkeller83** [comment]
The classes error prevents me from testing the newest radiowidget code in your latest commit

**Comment by mdipierro** [comment]
silly me. fixed.

**Comment by Kkeller83** [comment]
Ok its working now! Ready to merge I think. Thank you! :)

**Comment by mdipierro** [comment]
Thank you for all the help. :-)

**Comment by Kkeller83** [comment]
Overwriting a form widget with a custom widget class (Jims example at the beginning of this pr discussion, the newhtmxautocomplete) is not working anymore

**Comment by Kkeller83** [comment]
Moving the widget code from the model to the controller fixes it. So nevermind it works.

**Pull request merged**
