### PR TITLE
GitHub dashboards

### PR DESCRIPTION
**Pull request by ali96343**
These great frontend examples (ported on py4web) may be useful for py4web developers and users

https://github.com/ColorlibHQ/AdminLTE   - 135 MB
https://github.com/themesberg/volt-bootstrap-5-dashboard 30 MB
https://github.com/BulmaTemplates/bulma-templates 10 MB

### CODE REVIEW

**Comment by Kkeller83** [comment]
This is awesome but we probaly need to move those into a separate repo
given their size.

**Comment by ali96343** [comment]
I personally prefer the black screen of the cisco-router and the vim-editor, but a modern forend cannot be small. 
We don't have enough disk space ?
Here is a separate repo https://github.com/ali96343/facep4w  - 1GB

**Comment by Kkeller83** [comment]
Super!

Disk space is usually not the problem but if someone wants to download a
framework they just don't expect over 100mb etc I think.

But that is up to Massimo.

I guess most devices from PC to raspberry pi could handle the space
required.

It's just unusual.

Let's see what Massimo thinks

**Comment by ali96343** [comment]
Why in the JS world no one thinks about the size of the application and the size of the nodejs directory ?
Beautiful py4web should have real demo applications,   such as AdminLTE .... etc

**Comment by mdipierro** [comment]
Agree. Feel free to add prominent links from examples and documentation to
your templates

**Comment by mdipierro** [comment]
To clarify my previous comment. I am happy to host these apps on the same webside as the main page but this belongs to another repo and links from the examples app. I can create the repo but since you are doing all the work, I think you should create it and I would use it. ;-)

**Comment by ali96343** [comment]
ok,  This is  a good solution.
Thanks

**Pull request closed without merging**
