### PR TITLE
include current query_string when redirecting to select

### PR DESCRIPTION
**Pull request by jpsteil**
When redirecting to 'select' pass along any query parameters that were included in the original request.  Currently the query_string is lost when redirecting to 'select'

### CODE REVIEW

**Comment by jpsteil** [comment]
@massimo - any concerns with this PR?  Would be really helpful for me to get this merged.  The redirect to /select on grid is not working without this.

**Comment by mdipierro** [comment]
overlooked it. will review tomorrow

**Comment by jpsteil** [comment]
@mdipierro - still waiting for this PR.  I can't move to the latest py4web without it, breaks all my htmx integration.  Hoping we can get this merged before the weekend.

**Comment by mauriziobrilli** [comment]
Hi @mdipierro. Please complete your review and merge. Without it I'm stuck, too.

**Pull request merged**
