### PR TITLE
chapter review: make use of ReST comments for things to fix (search f…

### PR DESCRIPTION
**Pull request by paolopas**
1. fixed examples for Python3 (most prints and long ints)
2. addes ReST comments (with FIXMEs) for things still to fix
3. fixed internal crosslinks (maybe @nicozanf is interested in actual usage of :ref:)
4. somewhere needed to cite web2py explicitly

and more

### CODE REVIEW

**Comment by paolopas** [comment]
disable syntax highlight on literal blocks (::)

- speed up sphinx
- force authors to use code-block directive (.. code:: ...) with right Pygment lexer alias

**Comment by paolopas** [comment]
see
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-literal-blocks

**Comment by nicozanf** [comment]
It's OK for me. Using the FIXME ReST comment is a good idea. Grazie Paolo!

**Comment by paolopas** [comment]
Near 1 MB space saved in docs/images, pdf goes from 3.2 MB to 2.4 MB

**Pull request merged**
