### PR TITLE
Fix checkbox widget - remove disabled='' AND grid fix

### PR DESCRIPTION
**Pull request by jpsteil**
With disabled='' in the checkbox attrs, all checkboxes are disabled.

### CODE REVIEW

**Comment by jpsteil** [comment]
Added another pretty significant fix to this PR that fixes a problem in grid.py.  The latest grid cleanup pr broke the case where you pass a query to a grid but don't specify the fields.  If the ID field is not readable then it isn't included in the needed_fields list.  The latest commit here fixes that by dedenting the check for that situation out of the else of the if structure.

**Comment by jpsteil** [comment]
Ok, now I'm confused.  The grid fix I supplied is needed in my test environment, but not my production env.  In test I get an error on because the 'id' field isn't included in needed_fields.  But in production it works.  Here is the error I get in test:

```
ERROR:root:Traceback (most recent call last):
  File "/home/jim/dev/py4web/py4web/core.py", line 866, in wrapper
    ret = func(*func_args, **func_kwargs)
  File "/home/jim/dev/py4web/py4web/core.py", line 819, in wrapper
    ret = obj.transform(ret, shared_data)
  File "/home/jim/dev/py4web/py4web/core.py", line 523, in transform
    output = yatl.render(
  File "/home/jim/.local/lib/python3.8/site-packages/yatl/template.py", line 968, in render
    exec(code, context)
  File "<string>", line 59, in <module>
  File "/home/jim/dev/py4web/py4web/utils/grid.py", line 1159, in render
    return self.render_table()
  File "/home/jim/dev/py4web/py4web/utils/grid.py", line 1124, in render_table
    table.append(self.render_table_body())
  File "/home/jim/dev/py4web/py4web/utils/grid.py", line 913, in render_table_body
    row_id = row["id"]
  File "/home/jim/.local/lib/python3.8/site-packages/pydal/objects.py", line 146, in __getitem__
    raise KeyError(key)
KeyError: 'id'```

So, not sure if this should be pulled or not.  Massimo - if you could review and comment I'd appreciate it.  If there is a way for you to merge the form.py changes and leave the grid change for review, that would be great.  Ran out of time tonight to dig deeper.

-Jim

**Comment by jpsteil** [comment]
On my test box in py4web root I used pip3 install --upgrade -r requirements.txt

Made no difference, I'm still getting the error in my test environment.

**Comment by Kkeller83** [comment]
After the latest merge for the grid I did a fresh py4web clone just now in
a fresh virtual environment and then pulled your htmx demo app.

I see for customer_line_orders you do not require the id field.

And all works as expected.

Is that any helpful?

https://github.com/jpsteil/py4web_htmx_demo/blob/472da0ab1af0e352c389d019dc244b1b987af3a1/controllers.py#L148




snippet:

 grid = Grid(
        path,
        fields=[
            db.product.name,
            db.order_line.quantity,
            db.product.price,
            db.order_line.price,
        ],
        headings=["PRODUCT", "QTY", "UNIT", "EXT"],
        query=reduce(
            lambda a, b: (a & b),
            [db.order_line.order == order_id],
        ),
        left=left,
        orderby=[db.order_line.id],
        auto_process=False,
        rows_per_page=5,
        grid_class_style=GridClassStyleBulma,
        formstyle=formstyle,



Am Mi., 23. Juni 2021 um 07:07 Uhr schrieb mdipierro <
***@***.***>:

**Comment by Kkeller83** [comment]
removing the line where you define which field you want and setting
product.id and customer_line.id readable to False before the query also
does not seem to break things here:

if path and path.split("/")[0] in ["new", "details", "edit"]:
        db.order_line.price.readable = False
        db.order_line.price.writable = False


    formstyle = FormStyleFactory()
    formstyle.classes = FormStyleBulma.classes
    formstyle.class_inner_exceptions = FormStyleBulma.class_inner_exceptions
    formstyle.widgets["product"] = NewHtmxAutocompleteWidget(
        url=URL("product_autocomplete"), order_id=order_id
    )

*    db.product.id.readable=False    db.order_line.id.readable=False*

    grid = Grid(
        path,
      * *removed list of fields here**
        headings=["PRODUCT", "QTY", "UNIT", "EXT"],
        query=reduce(
            lambda a, b: (a & b),

Am Mi., 23. Juni 2021 um 09:53 Uhr schrieb Kevin Keller ***@***.***

**Pull request merged**
