### PR TITLE
Added the ability to create new files from dashboard app

### PR DESCRIPTION
**Pull request by ch-rigu**
Hi, 
I've write the function that creates new files from the admin dashboard :), adapt it if necessary.
btw, you mind if I create a option to select a different appearance (future.css) ?. The actual colors are hard to use during the day... would be nice to have different appearances to the admin dashboard.

Cheers.
Chris.

### CODE REVIEW

**Comment by mdipierro** [comment]
Thanks. Good job. Made some minor changes. Please check I did not break it. ;-)

**Comment by ch-rigu** [comment]
Hi Massimo, it works but is trying to write in any place in the file system, if you pass an argument starting with "/" like: /blabla/file.html, it will try to create the folder in the system root directory.
Do you want me to fix this or you will do it ?

Cheers.
Chris.

**Comment by mdipierro** [comment]
My bad! can you fix it? something like this:

fullpath = os.path.join(path, filename)
if not paths.startswith(path + os.sep): error

**Comment by ch-rigu** [comment]
> My bad! can you fix it? something like this: fullpath = os.path.join(path, filename) if not paths.startswith(path + os.sep): error

Sure! I'll do it.

**Pull request merged**
