### PR TITLE
fixed apps_folder usage

### PR DESCRIPTION
**Pull request by paolopas**
Unchecked (i.e. not existing) apps_folder allowed on **setup** and **new_app** commands only.
Other py4web commands need existing apps_folder and ask for creation of missing `__init__.py`.
See #444 for other fixed issues.

### CODE REVIEW

**Comment by mdipierro** [comment]
Let's talk about this. The apps folder name could have any arbitrary name and it must be specified when py4web starts. BUT when an app wants to include a module from another app it should just be able to do: "import apps.otherapp.modulename". In other words I want the module that corresponds to the folder to always be referred to as "apps" in code. I think this PR break that

**Comment by mdipierro** [comment]
I think unchecked app folder should be allowed for setup only. I made a commit for that following your suggesting to address failing tests.

**Comment by paolopas** [comment]
Massimo,
I was complaining about harcoded 'apps' since my PR #438 ...

well, in that case I suppose that you want to see my wonderful

**Comment by paolopas** [comment]
More important, now "import apps.sub" does not relies on having the APPS_FOLDER visible from current working directory to work!

**Pull request merged**
