### PR TITLE
fixed core

### PR DESCRIPTION
**Pull request by dkawasaka**
fixed core
prevent class name error

### CODE REVIEW

**Comment by mdipierro** [comment]
Is this in response to a ticket? Can you help me reproduce the error that requires this fix?

**Comment by dkawasaka** [comment]
> Is this in response to a ticket? Can you help me reproduce the error that requires this fix?

on the dashboard
when I open a table, but not all of them, only some return the error:
type object 'Session' has no attribute '_Fixture__name'

**Comment by mdipierro** [comment]
I am going to try reproduce this first. Something is wrong and the try except will only mask the real problem. Thanks for bringing this up.

**Comment by mdipierro** [comment]
I think this was fixed in a different way.

**Pull request closed without merging**
